### ISSUE TITLE
Move Serialization to Json

### ISSUE THREAD

**Issue by sethjuarez** [sethjuarez/numl#31]
I am thinking of moving all serialization to json. Any thoughts?

**Comment by normanhh3** [comment]
Due to the numeric nature of the data being stored in the model, does it make sense to use something like [Protobuf-net](https://github.com/mgravell/protobuf-net) designed for compact serialization and efficient loading to be used for serialization?  Looks like @mgravell has outdone himself on this project.  It appears to support a host of configurations including mono and various phone platforms and the .NET Compact Framework back to 2.0!

**Comment by sethjuarez** [comment]
My goal is to have the serialized output be readable. Loading the models should be really fast (as they are not verbose) and happen only one time.

**Comment by normanhh3** [comment]
Then it sounds like json is the better tool. :-)
